from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle
)

from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.enums import TA_CENTER

from datetime import datetime


def generate_report(
    filename,
    user_name,
    total_expenses,
    budget,
    highest_expense,
    insights,
    category_data,
    status
):

    pdf = SimpleDocTemplate(filename)

    styles = getSampleStyleSheet()

    content = []

    title_style = styles["Title"]
    title_style.alignment = TA_CENTER

    heading_style = styles["Heading2"]
    heading_style.textColor = colors.HexColor("#2563eb")

    title = Paragraph(
        "FinPilot AI Financial Report",
        title_style
    )

    content.append(title)

    content.append(
        Spacer(1, 10)
    )

    generated_date = datetime.now().strftime(
        "%d %B %Y"
    )

    date_para = Paragraph(
        f"Generated on: {generated_date}",
        styles["Normal"]
    )

    content.append(date_para)

    content.append(
        Spacer(1, 20)
    )

    summary_data = [
        ["Metric", "Value"],
        ["User", user_name],
        ["Budget", f"₹{budget}"],
        ["Total Expenses", f"₹{total_expenses}"],
        ["Highest Expense", f"₹{highest_expense}"],
        ["Generated On", generated_date]
    ]

    summary_table = Table(
        summary_data,
        colWidths=[200, 250]
    )

    summary_table.setStyle(
        TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#2563eb")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("GRID", (0, 0), (-1, -1), 1, colors.black),
            ("BACKGROUND", (0, 1), (0, -1), colors.lightgrey),
            ("ROWBACKGROUNDS", (0,1), (-1,-1),
             [colors.whitesmoke, colors.lightgrey])
        ])
    )

    content.append(
        Paragraph(
            "Financial Summary",
            heading_style
        )
    )

    content.append(
        Spacer(1, 10)
    )

    content.append(summary_table)

    content.append(
        Spacer(1, 20)
    )

    if status == "Safe":
        status_color = colors.green

    elif status == "Warning":
        status_color = colors.orange

    else:
        status_color = colors.red

    status_table = Table(
        [["Budget Status", status]],
        colWidths=[200, 250]
    )

    status_table.setStyle(
        TableStyle([
            ("GRID", (0,0), (-1,-1), 1, colors.black),
            ("BACKGROUND", (0,0), (0,0), colors.lightgrey),
            ("BACKGROUND", (1,0), (1,0), status_color),
            ("TEXTCOLOR", (1,0), (1,0), colors.white),
            ("FONTNAME", (0,0), (-1,-1), "Helvetica-Bold")
        ])
    )

    content.append(
        Paragraph(
            "Budget Health",
            heading_style
        )
    )

    content.append(
        Spacer(1, 10)
    )

    content.append(status_table)

    content.append(
        Spacer(1, 20)
    )

    content.append(
        Paragraph(
            "Category Breakdown",
            heading_style
        )
    )

    content.append(
        Spacer(1, 10)
    )

    category_table_data = [
        ["Category", "Amount"]
    ]

    for category, amount in category_data.items():

        category_table_data.append(
            [category, f"₹{amount}"]
        )

    category_table = Table(
        category_table_data,
        colWidths=[220, 220]
    )

    category_table.setStyle(
        TableStyle([
            ("BACKGROUND", (0,0), (-1,0), colors.HexColor("#10b981")),
            ("TEXTCOLOR", (0,0), (-1,0), colors.white),
            ("FONTNAME", (0,0), (-1,0), "Helvetica-Bold"),
            ("GRID", (0,0), (-1,-1), 1, colors.black),
            ("ROWBACKGROUNDS", (0,1), (-1,-1),
             [colors.whitesmoke, colors.lightgrey])
        ])
    )

    content.append(category_table)

    content.append(
        Spacer(1, 20)
    )

    content.append(
        Paragraph(
            "AI Insights",
            heading_style
        )
    )

    content.append(
        Spacer(1, 10)
    )

    for insight in insights:

        content.append(
            Paragraph(
                f"• {insight}",
                styles["Normal"]
            )
        )

        content.append(
            Spacer(1, 5)
        )

    content.append(
        Spacer(1, 20)
    )

    footer = Paragraph(
        "Generated by FinPilot AI",
        styles["Italic"]
    )

    content.append(footer)

    pdf.build(content)